# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-LibXML-XPathContext
version:      0.05
version_from: XPathContext.pm
installdirs:  site
requires:
    XML::LibXML:                   1.51

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
